config:
  system:
    name: miaosha_system
    host: 127.0.0.1
    port: 8080
    env: dev
  mysql:
    host: 127.0.0.1
    port: "3306"
    db: miaosha_system
    user: root
    pwd: qwer0209
    logLevel: dev
    config: charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    pwd: "123456"
    db: 1
  logger:
    level: info
    prefix: '[miaosha_system]'
    director: log
    showLine: true
    logInConsole: true
  jwt:
    signKey: 'spikes123456'
    expireTime: 3600
    issuer: 'spikes'


